# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

before_install:
    # Remove homebrew.
    - brew remove --force --ignore-dependencies $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda2-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda2/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels fermi_dev_externals
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-build

script:
  - conda build .

  # - upload_or_check_non_existence ./recipe conda-forge --channel=main

